services:
  web:
    container_name: "${COMPOSE_WEB_CONTAINER}"
    image: "${COMPOSE_WEB_IMAGE}"
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/code

  db:
    container_name: "${COMPOSE_DB_CONTAINER}"
    image: postgres
    ports:
      - "5543:5432"
    environment:
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: postgres_fastapi_template
      POSTGRES_USER: user
